# QA environment values
image:
  tag: "qa"  # CI/CD will update this with actual image tag

ingress:
  enabled: true
  className: nginx
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: ${{values.team}}-${{values.application_id}}-qa.${{values.fqdn}}
    dns.gardener.cloud/ttl: "180"
  hosts:
    - host: ${{values.team}}-${{values.application_id}}-qa.${{values.fqdn}}
      paths:
        - path: /
          pathType: ImplementationSpecific
