teams:
# new team stanza for team admins
  - name: admins
    sourceRepos:
      - 'https://github.com/nphaseinc/model-kubrix-app.git'
      - 'https://github.com/kkumar-devops/kubrix-model-airflow.git'
      - 'https://github.com/kkumar-devops/testing-kuberix.git'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/nphaseinc/model-kubrix-app.git
      path: demo-apps
      revision: master
    multiStageKargoAppSet:
      github:
        organization: nphaseinc
      repositoryMatch: ^model-kubrix-app
