teams:
# new team stanza for team admins
  - name: admins
    sourceRepos:
      - 'https://github.com/nphaseinc/admins-*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/nphaseinc/admins-apps
      path: demo-apps
      revision: main
    multiStageKargoAppSet:
      github:
        organization: nphaseinc
