{{- range $team := .Values.teams }}
{{/* Create a single GitHub credential per team that matches all GitHub repos */}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $team.name }}-github-credential
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ $team.name }}-github-credential
    template:
      metadata:
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        password: "{{ `{{ .KUBRIX_ARGOCD_APPSET_TOKEN }}` }}"
        username: "dummy"
        url: "https://github.com"
  data:
  - secretKey: KUBRIX_ARGOCD_APPSET_TOKEN
    remoteRef:
      key: kubrix-kv/data/{{ $team.name }}/delivery
      property: KUBRIX_ARGOCD_APPSET_TOKEN
---
{{- end }}

